### ISSUE TITLE
songs overlap (area + fighting theme) 

### ISSUE THREAD

**Issue by Miepee** [TheyCallMeXander/AM2R-SA-X-Duels#11]

**Comment by TheyCallMeXander** [comment]
- Chase Music does not end in certain scenarios
- Spectator swaps don't always grab new Room music theme (if room doesn't set new music)

**Comment by TheyCallMeXander** [comment]
Wontfix on the Spectator music bug, since it's far too complicated and would require adding a mus_change to every room that doesn't have one, opr indexing every room and putting them under "music groups"

**Comment by TheyCallMeXander** [comment]
Chase music should now always fadeout if Chase is inactive
Main Boss themes should now always clear if not in their boss room
