### ISSUE TITLE
Player Count fluctuate while paused

### ISSUE THREAD

**Issue by Ehseezed** [TheyCallMeXander/AM2R-SA-X-Duels#50]
The player count is cringe while paused with spectators

**Comment by TheyCallMeXander** [comment]
Lobby Paused is displaying Spectators as players on the Player Counter, resolves when Lobby becomes active.

**Comment by TheyCallMeXander** [comment]
Issue is with Spectators not counting as "dead" on a paused lobby. band-aid patch is to make it not show playercount at all :)
